version: "3"
services:
  roach1:
    image: docker.io/cbuschka/cockroach-dev:v21.1.11-2
    hostname: roach1
    environment:
      - COCKROACH_HTTP_ADDR=0.0.0.0:8443
      - COCKROACH_ADVERTISE_ADDR=localhost:26257
      - COCKROACH_LISTEN_ADDR=0.0.0.0:26257
      - COCKROACH_CERTS_DIR=/cockroach/cockroach-certs
      - COCKROACH_SECURITY_MODE=secure
      - COCKROACH_ROOT_PASSWORD=asdfasdf
      - COCKROACH_DATABASE=develop
      - COCKROACH_USER=developer
      - COCKROACH_PASSWORD=asdfasdf
    ports:
      - "26257:26257"
      - "8443:8443"
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    volumes:
      - roach1-data:/cockroach/cockroach-data/:Z
      - roach1-certs:/cockroach/cockroach-certs/:Z
    networks:
      roachnet:

volumes:
  roach1-data:
  roach1-certs:

networks:
  roachnet:
